version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: url-shortener-app
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www/html
    environment:
      APP_ENV: local
      APP_DEBUG: 1
      APP_KEY: base64:somegeneratedkey
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: shortner_db
      DB_USERNAME: root
      DB_PASSWORD: ""
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: url-shortener-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: shortner_db
      MYSQL_USER: root
      MYSQL_PASSWORD: ""
    ports:
      - "3307:3306"   # Exposes MySQL at localhost:3307
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
